### ISSUE TITLE
Is there a PyTorch implementation of this project?

### ISSUE THREAD

**Issue by theneotopia** [nestorSag/streaming-gmm#1]
Hi @nestorSag , 
I'm going to fit a GMM in a mini batch training manner, which vanilla EM algorithm is not suitable. And after Google for a while, I found this repo may be helpful. But my work is mainly based on PyTorch. So I want to ask have you ever implemented this repo in PyTorch?
Thanks.

**Comment by nestorSag** [comment]
Hi @yangzhaopeng3, I'm afraid I didn't, but i _think_ [this repo](https://github.com/bayesiains/scalable_xd) does a similar thing using PyTorch ([here's ](https://arxiv.org/pdf/1911.11663.pdf) the corresponding paper, look at section 3); there's a folder there called `gmm`. I hope that helps.

**Comment by theneotopia** [comment]
> Hi @yangzhaopeng3, I'm afraid I didn't, but i _think_ [this repo](https://github.com/bayesiains/scalable_xd) does a similar thing using PyTorch ([here's ](https://arxiv.org/pdf/1911.11663.pdf) the corresponding paper, look at section 3); there's a folder there called `gmm`. I hope that helps.

Sorry for my late reply. Thanks a lot, Nestor! @nestorSag
